apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.network/ckan-default: "true"
        io.kompose.service: solr
    spec:
      initContainers:
      - name: permissions
        image: busybox
        command: ["chmod", "-R", "777", "/var/solr"]
        volumeMounts:
        - name: solr-data
          mountPath: /var/solr
      containers:
        - image: ckan/ckan-solr:2.9-solr8
          livenessProbe:
            exec:
              command:
                - wget
                - -qO
                - /dev/null
                - http://localhost:8983/solr/
          name: solr
          resources: {}
          volumeMounts:
            - mountPath: /var/solr
              name: solr-data
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
          
status: {}
